### PR TITLE
fix: commit missing monero settings

### PR DESCRIPTION
**Pull request by brianp**
Description
---
Missed updating these monero settings in the last PR.

Motivation and Context
---
Set to the mainnet community wallet.

How Has This Been Tested?
---
manually

### CODE REVIEW

**Comment by brianp** [comment]
Ignore the license failure, it does that sometimes.

**Review by hansieodendaal — APPROVED** [review]
utACK

**Review by hansieodendaal — COMMENTED** [review]
This ok?

image

**Comment by brianp** [comment]
> Thought it would be populated.

It's most likely because you had an existing settings file. You'd have to wipe that file and start fresh.

**Review by SWvheerden — APPROVED** [review]

**Pull request merged**
